### ISSUE TITLE
Changing metamask chain after user is connected from web3connect

### ISSUE THREAD

**Issue by xsaad67** [web3ui/web3uikit#1004]
How can i change the chain of user once it gets connected from the metamask?

**Comment by AbhinavMV** [comment]
Hey @xsaad67,

Apologies for the late reply 😅 
Switching a network functionality is not present in web3uikit **Yet** !!

You can use wagmi or ethers package to switch the network easily
From a quick google search - https://davidkathoh.medium.com/programatically-switch-network-on-metamask-e9a44525cab

Hope this helps, if you have more queries please join our discord channel and we will be happy to help you 🙌🏻 

Will close this issue since its not related to web3uikit and we have similar plans to work on the kit, hope you understand 🙇🏻
