### ISSUE TITLE
textArea needs a codeArea alternative

### ISSUE THREAD

**Issue by BillyG83** [web3ui/web3uikit#221]
- we need this to complete the new Admin design
- TextArea with an optional layout prop for 'text' | 'code' default test of course
- should match design supplied below

<img width="582" alt="code area design" src="https://user-images.githubusercontent.com/13779759/157067856-36285a76-fb4a-433a-a7cc-163536cccf15.png">

**Comment by mubarakone** [comment]
Do you want the codeArea to be a seperate component from textArea? Or do you want a textArea that has the option to change from standard text to code? Interested in this

**Comment by mubarakone** [comment]
Im just going to add it as an extra type option as seen here:
![image](https://user-images.githubusercontent.com/52806204/157122387-aa780123-0733-4272-af37-bd4ac1e1f940.png)

**Comment by BillyG83** [comment]
hey @mubarakone i would love if if you added to TextArea component please 🙏 
and could make it look like the design

**Comment by BillyG83** [comment]
I have assigned this issue to you @mubarakone if you dont want it just assign it back to me bud =]

**Comment by mubarakone** [comment]
I understand you don't want to add any extra dependencies, however I feel like with this one we might not have a choice, ONLY for the sake of efficiency. 
The numbers on the side is what I'm struggling with. I can create it from scratch, however for the sake of this project, it wouldn't be wise because issues in the future could arise and it would be hard to debug. So I was thinking our best option is to include this dependency I found: https://github.com/FormidableLabs/prism-react-renderer
It is very light dependency, I can remove the highlights and themes to match the design you provided, all very simple and interactable with the existing code. 
Please let me know what you think!

**Comment by locothedev** [comment]
https://github.com/web3ui/web3uikit/pull/322
