### ISSUE TITLE
[Feat]: Input component to also allow `Blockie` instead of an icon

### ISSUE THREAD

**Issue by dani69654** [web3ui/web3uikit#271]
Implementing the following as per designer req.
![Screenshot 2022-03-11 at 15 25 52](https://user-images.githubusercontent.com/60792849/157886249-9804689f-f173-4193-b89a-0961a39eb2ac.png)

**Comment by AbhinavMV** [comment]
Hey @osamajandali 
instead of writing entirely new code maybe we can use Blockie component.
In Button> type.tsx
```tsx
prefixIcon?: TIconType | 'blockie';
blockieSeed?: string;
```
And then in Button.tsx
```tsx
<DivStyled className="input_prefixIcon">
      {prefixIcon !== 'blockie' && <Icon svg={prefixIcon} />}
      {prefixIcon === 'blockie' && <Blockie seed={blockieSeed} />}
</DivStyled>
```
Let me know if you need any help 😄

**Comment by osamajandali** [comment]
@AbhinavMV I already did that but the problem isn’t here in the blockie the problem was with the text being ellipsed on blur
![image](https://user-images.githubusercontent.com/13832392/166105377-7604a6fe-fe47-4fb8-93aa-9c7aa62be3ff.png)

and you can check here it's done #396, need some code refactor only
