### ISSUE TITLE
Feature request: Connect metamask mobile version onclick

### ISSUE THREAD

**Issue by Leonardll** [web3ui/web3uikit#617]
Hi guys, i have made a dapp using web3uikit button and noticed than on mobile, it does not call the metamask mobile app.
Could you implement this for the community please?

**Comment by BillyG83** [comment]
@Y0moo do you think this is possible?

**Comment by Y0moo** [comment]
Do you mean it doesn't work when you are using the Metamask Browser?

**Comment by Leonardll** [comment]
> Hey @Leonardll! Do you mean it doesn't work when you are using the Metamask Browser?

Hey Yomoo, i mean that it doesn't call the metamask mobile app when clicking on the icon. It does not open it at all. 

Thanks for looking into it

:)

**Comment by YosephKS** [comment]
Hey @BillyG83 @Y0moo the thing is that the metamask code only can be used in browser that is injected with `window.ethereum`, which is only the case in desktop browser with metamask plugin installed or metamask moblie in-app browser.

If he wants to call metamask mobile directly from mobile, he can only do it by calling the WalletConnect auth function since metamask mobile is WC-compatible 🙌🏼

**Comment by osamajandali** [comment]
Thanks @Y0moo , @YosephKS 

I hope that your question is being answered..feel free to re-open the issue if you need more answers
