### ISSUE TITLE
Select component defaultOptionIndex - how to insert an index of currently connected chain

### ISSUE THREAD

**Issue by spavlovic77** [web3ui/web3uikit#70]
I use useEffect to get networkID in order to get defaultOptionIndex to be used.

const [defaultOption, setDefaultOption] = useState()
useEffect(() => {
  if (networkId==5777) {setDefaultOption ('0')}
  else if (networkId=97) {setDefaultOption('1')}
  else if (networkId=8001){setDefaultOption('2')}
}, [])

After that I would like to use defaultOption in Select component as follows:

<Select
              defaultOptionIndex={`${defaultOption}`}
              label="Select other Chain"
              onChange={(e) => handleNetworkSwitch(e.id)}
              options={[
                {
                  id: 'polygonTST',
                  label: 'Polygon',
                  prefix: <PolygonLogo/>
                },
                {
                  id: 'bsc',
                  label: 'BSC',
                  prefix: <BSCLogo/>
                },
                {
                  id: 'ganache',
                  label: 'Ganace',
                  prefix: <AvaxLogo/>
                }
              ]}
            />

The Issue I have is that does not work and the default is not set to the connected network.

**Comment by rayyan224** [comment]
Hey, I hope you are well. Took your code for a spin, the problem here is not really the WebKit but the implementation. 
First off, in your useEffect, in your if else's you have = it should ==. 
Secondly, in React useEffects works parallel with the render, so setting a variable in a use effect may not always be defined sometimes it is defined after the render. There are two ways of handling such a situation. The first is just setting the value within the setState function for your state. The second, way which we can handle the situation preferred way is to conditionally render the Select object. What was happening was the defualtionOption variable was undefined when you passed it to the state component. Thus it didn't work. So we can use some simple JSX to only render the Select, if the defaultOption is defined this will ensure that is rendered once the useEffect is finsihed. 
Code would look like this:
1. UseEffect
```
const [defaultOption, setDefaultOption] = useState();
  useEffect(() => {
    if (networkId == 5777) {
      setDefaultOption(1);
    } else if (networkId == 97) {
      setDefaultOption(2);
    } else if (networkId == 8001) {
      setDefaultOption(3);
    }
    console.log("defualt Optio", defaultOption);
  }, []);

```
JSX:

```
{defaultOption && (
        <Select
          defaultOptionIndex={defaultOption}
          label="Select other Chain"
          onChange={(e) => handleNetworkSwitch(e.id)}
          options={[
            {
              id: "polygonTST",
              label: "Polygon",
              prefix: "",
            },
            {
              id: "bsc",
              label: "BSC",
              prefix: "",
            },
            {
              id: "ganache",
              label: "Ganace",
              prefix: "",
            },
          ]}
        />
      )}

```
Hope this helps! ✌️

**Comment by spavlovic77** [comment]
Thanks you very much. It helped.
