### ISSUE TITLE
NFTBalance with ERC1155 and all <NFT/> options

### ISSUE THREAD

**Issue by Kipperlenny** [web3ui/web3uikit#724]
**first**: as far as I can see, I cannot use the options from `<NFT>` in the `<NFTBalance>` Tag right?

**Second and more important:** 
My NFTs are ERC1155, but they show up as ERC721.
And I have more than one of them, but I cannot see any "count" on the cards...

**Comment by AbhinavMV** [comment]
yes, the contract type does seem to be a bug with the component. 
TY for letting us know  🙌🏻 
We will be releasing our monorepo soon. And this will be fixed after that release 🙌🏻 

fetchMetadata does not need to be used in the `NFTBalance` component since it uses `Web3Api.account.getNFTs` api from moralis to get the data.

**Comment by AbhinavMV** [comment]
Hey @Kipperlenny 
This issue is fixed in our latest monorepo. 
Give it a try. And let us know if you feel there is any issue

Closing this now.
