### ISSUE TITLE
[Checkbox]: Better styles

### ISSUE THREAD

**Issue by AbhinavMV** [web3ui/web3uikit#811]
![image](https://user-images.githubusercontent.com/35369843/192695378-7470604c-bb94-42b5-8751-42b3bad26218.png)

Currently its using position absolute.
convert it to flex(or grid) to allow more customization such as `align-items:center`

**Comment by BillyG83** [comment]
that wont work so well i do not think @AbhinavMV because creating the fake box and tick is done with `:before` and `:after` however with a fixed hieght you could make it always center by using

```
top: calc(50% - (height / 2))
```

but do not neglest all the other functionality like line wrapping just to fit with this design. If i were you i would have

```
<DivStyledFlex>
  <CheckBox />
  <Illustration />
  <label />
</DivStyledFlex>
```

as this is on one off just for Admin

**Comment by AbhinavMV** [comment]
Yeah @BillyG83 this won't work 🙌🏻
I will create a custom checkbox for admin, Can't use this one as all its style are dependent on label.
Will have to refactor this component.. there is also one other issue to remove its controlled state or something.
Anyway will close this for now. TY for letting me know early, appreciate it 🙌🏻
